name: "Setup and install"
description: "Common setup steps for Actions"

jobs:
  setup-uv:
    name: python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v5
        with:
        python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v6