name: "Setup and install"

description: "Common setup steps for Actions"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --locked --all-extras --dev