"""make user id nullable in contact

Revision ID: 0da0b69b9552
Revises: d183b60f6142
Create Date: 2025-11-06 23:54:28.199355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0da0b69b9552"
down_revision: Union[str, Sequence[str], None] = "d183b60f6142"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contact", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contact", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
