"""add subject to contact table

Revision ID: 1203cb2a9fb9
Revises: 0da0b69b9552
Create Date: 2025-11-07 14:55:47.317221

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1203cb2a9fb9'
down_revision: Union[str, Sequence[str], None] = '0da0b69b9552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('subject', sa.String(), nullable=True, server_default=""))

    op.execute("UPDATE contact SET subject = '' WHERE subject IS NULL")

    op.alter_column('contact', 'subject', nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'subject')
    # ### end Alembic commands ###
