"""add token column to verification code

Revision ID: 20a7f21f562e
Revises: a5b5f6c6c1ca
Create Date: 2025-11-09 22:38:30.325918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a7f21f562e'
down_revision: Union[str, Sequence[str], None] = 'a5b5f6c6c1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_code', sa.Column('token', sa.String(), nullable=False))
    op.create_index(op.f('ix_verification_code_token'), 'verification_code', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_code_token'), table_name='verification_code')
    op.drop_column('verification_code', 'token')
    # ### end Alembic commands ###
