"""add columns to user

Revision ID: 670b5ad262b2
Revises: c475b0275da4
Create Date: 2025-11-11 00:14:01.802701

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "670b5ad262b2"
down_revision: Union[str, Sequence[str], None] = "c475b0275da4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add columns as nullable with server_default
    op.add_column(
        "user", sa.Column("first_name", sa.String(), nullable=True, server_default="")
    )
    op.add_column(
        "user", sa.Column("last_name", sa.String(), nullable=True, server_default="")
    )

    # Step 2: Populate existing rows with default values (quote "user" table name)
    op.execute("UPDATE \"user\" SET first_name = '' WHERE first_name IS NULL")
    op.execute("UPDATE \"user\" SET last_name = '' WHERE last_name IS NULL")

    # Step 3: Alter columns to be non-nullable and remove server_default
    op.alter_column("user", "first_name", nullable=False, server_default=None)
    op.alter_column("user", "last_name", nullable=False, server_default=None)

    # Drop the old name column
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=False)
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
