"""add indexes to account

Revision ID: 7aa956ee80f7
Revises: 670b5ad262b2
Create Date: 2025-11-13 21:00:05.684246

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aa956ee80f7"
down_revision: Union[str, Sequence[str], None] = "670b5ad262b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_account_account_id"), "account", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_account_provider_id"), "account", ["provider_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_provider_id"), table_name="account")
    op.drop_index(op.f("ix_account_account_id"), table_name="account")
    # ### end Alembic commands ###
