"""empty message

Revision ID: a22517529812
Revises: 5fe51f3dd69f
Create Date: 2025-10-08 11:56:29.010076

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a22517529812"
down_revision: Union[str, Sequence[str], None] = "5fe51f3dd69f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("caregiver_to_specialty_caregiver_information_id_fkey"),
        "caregiver_to_specialty",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("caregiver_to_specialty_specialty_id_fkey"),
        "caregiver_to_specialty",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "caregiver_to_specialty",
        "caregiver_information",
        ["caregiver_information_id"],
        ["user_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "caregiver_to_specialty",
        "specialty",
        ["specialty_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("careseeker_to_specialty_careseeker_information_id_fkey"),
        "careseeker_to_specialty",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("careseeker_to_specialty_specialty_id_fkey"),
        "careseeker_to_specialty",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "careseeker_to_specialty",
        "specialty",
        ["specialty_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "careseeker_to_specialty",
        "careseeker_information",
        ["careseeker_information_id"],
        ["user_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("user_to_role_role_id_fkey"), "user_to_role", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("user_to_role_user_id_fkey"), "user_to_role", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "user_to_role",
        "role",
        ["role_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "user_to_role",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_to_role", type_="foreignkey")
    op.drop_constraint(None, "user_to_role", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_to_role_user_id_fkey"), "user_to_role", "user", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("user_to_role_role_id_fkey"), "user_to_role", "role", ["role_id"], ["id"]
    )
    op.drop_constraint(None, "careseeker_to_specialty", type_="foreignkey")
    op.drop_constraint(None, "careseeker_to_specialty", type_="foreignkey")
    op.create_foreign_key(
        op.f("careseeker_to_specialty_specialty_id_fkey"),
        "careseeker_to_specialty",
        "specialty",
        ["specialty_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("careseeker_to_specialty_careseeker_information_id_fkey"),
        "careseeker_to_specialty",
        "careseeker_information",
        ["careseeker_information_id"],
        ["user_id"],
    )
    op.drop_constraint(None, "caregiver_to_specialty", type_="foreignkey")
    op.drop_constraint(None, "caregiver_to_specialty", type_="foreignkey")
    op.create_foreign_key(
        op.f("caregiver_to_specialty_specialty_id_fkey"),
        "caregiver_to_specialty",
        "specialty",
        ["specialty_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("caregiver_to_specialty_caregiver_information_id_fkey"),
        "caregiver_to_specialty",
        "caregiver_information",
        ["caregiver_information_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###
