"""fix user unique

Revision ID: a5b5f6c6c1ca
Revises: 1203cb2a9fb9
Create Date: 2025-11-08 18:20:33.853221

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5b5f6c6c1ca"
down_revision: Union[str, Sequence[str], None] = "1203cb2a9fb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=False)
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=True)
    # ### end Alembic commands ###
