"""create role table

Revision ID: bc58f003e05a
Revises: bf2fb1569e62
Create Date: 2025-10-06 11:21:11.264422

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "bc58f003e05a"
down_revision: Union[str, Sequence[str], None] = "bf2fb1569e62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
