"""remove role from session table

Revision ID: bdae7bf7508a
Revises: a22517529812
Create Date: 2025-10-11 14:07:20.026560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bdae7bf7508a"
down_revision: Union[str, Sequence[str], None] = "a22517529812"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session",
        sa.Column(
            "role",
            postgresql.ENUM("CARESEEKER", "CAREGIVER", "ADMIN", name="sessionroleenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
