"""drop unique idx

Revision ID: c475b0275da4
Revises: 20a7f21f562e
Create Date: 2025-11-09 22:39:09.282609

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c475b0275da4"
down_revision: Union[str, Sequence[str], None] = "20a7f21f562e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_code_value"), table_name="verification_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_verification_code_value"), "verification_code", ["value"], unique=False
    )
    # ### end Alembic commands ###
