"""add nullable columns to waitlist

Revision ID: d183b60f6142
Revises: bdae7bf7508a
Create Date: 2025-11-02 14:21:31.384136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd183b60f6142'
down_revision: Union[str, Sequence[str], None] = 'bdae7bf7508a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlist', 'referral_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('waitlist', 'notified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlist', 'notified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('waitlist', 'referral_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
