"""empty message

Revision ID: db4575e825ea
Revises: 7aa956ee80f7
Create Date: 2025-11-14 14:58:18.831098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db4575e825ea"
down_revision: Union[str, Sequence[str], None] = "7aa956ee80f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("caregiver_information", "profile_picture")
    op.drop_column("careseeker_information", "profile_picture")
    op.add_column(
        "user_information", sa.Column("profile_picture", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_information", "profile_picture")
    op.add_column(
        "careseeker_information",
        sa.Column("profile_picture", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "caregiver_information",
        sa.Column("profile_picture", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
